E2Helper.Descriptions["propFreeze"] = "freezes E if 1 unfreezes if 0."
E2Helper.Descriptions["propNotSolid"] = "0 makes prop solid, 1 will make prop not solid bewarned not solid props can pass through the world."
E2Helper.Descriptions["enableGravity"] = "0 disables gravity, 1 will enable."
E2Helper.Descriptions["drawShadow"] = "0 disables shadow, 1 will enable."
E2Helper.Descriptions["enableDrag"] = "0 disables drag, 1 will enable."